import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        backgroundColor: '#F4F5F7',
        minHeight: '100%',
        paddingTop: 45,
    },
    header: {
         width: '100%', // Ensures full width of the screen
        backgroundColor: '#D1D5DB', // Deep blue background for jumbotron effect
        paddingVertical: 50, // Larger padding for a more spacious feel
        paddingHorizontal: 20,
        shadowOffset: { width: 0, height: 10 },
        elevation: 8,
        marginTop: -45,
        marginBottom: 12,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 15, 
    },
   greeting: {
        fontSize: 32, 
        fontWeight: '900', 
        color: '#ffffff', 
        marginBottom: 8,
    },
    avatar: {
        marginLeft: 15,
        borderWidth: 3,
        borderColor: '#ffffff', 
    },
    welcome: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000', 
        textAlign: 'center',
        marginTop: 10,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 35,
        borderWidth: 1.5,
        borderColor: '#E5E7EB',
        paddingHorizontal: 22,
        margin: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 6,
    },
    searchIcon: {
        marginRight: 18,
        color: '#1F2937',
    },
    searchInput: {
        flex: 1,
        height: 55,
        backgroundColor: 'transparent',
        fontSize: 16,
        color: '#4B5563',
    },
    packageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 30,
        gap: 22,
    },
    slidableContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 3,
        paddingVertical: 14,
        backgroundColor: '#fff',
        borderRadius: 35,
        borderWidth: 1.5,
        borderColor: '#ffff',
        paddingHorizontal: 22,
        margin: 4,
        marginBottom: 30,
        elevation: 5,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 6,
    },
    packageCard: {
        paddingVertical: 12,
        paddingHorizontal: 22,
        borderRadius: 35,
        backgroundColor: 'trasnsparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 7,
        height: 55,
        width: 150,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: '#E5E7EB',
    },
    packageTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333333',
    },
    customText: {
        color: '#6B7280',
        fontSize: 15,
    },
    starterSection: {
        backgroundColor: '#F59E0B',
        borderRadius: 35,
        margin: 20,
        padding: 40,
        width: '90%',
        height: 460,
        zIndex: 999,
        marginTop: -45,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 12,
    },
    starterTitle: {
        fontSize: 26,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 22,
    },
    welcomeText: {
        color: '#D1D5DB',
        marginBottom: 30,
    },
    ctaContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#1F2937',
        padding: 12,
        borderRadius: 60,
        marginTop: 200,
    },
    seeMoreLink: {
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
        marginLeft: 45,
    },
    buyButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 60,
        width: 50,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buyButtonText: {
        color: '#1F2937',
        fontWeight: '700',
    },
    alignStart: {
        alignSelf: 'flex-start',
        color: '#1F2937',
        fontWeight: '600',
        fontSize: 17,
        marginBottom: 14,
        margin: 15
    },
    packageDetailsContainer: {
        marginTop: 45,
        padding: 0,
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 6,
        height: 350,
    },
});

export default styles;
