import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 20,
        backgroundColor: '#F4F5F7',
        minHeight: '100%',
        paddingTop: 40,
    },
    header: {
        marginBottom: 20,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    greeting: {
        fontSize: 26,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 10,
    },
    avatar: {
        marginLeft: 10,
    },
    welcome: {
        fontSize: 16,
        color: '#4B5563',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingHorizontal: 20,
        marginBottom: 25,
        elevation: 3,
    },
    searchIcon: {
        marginRight: 15,
        color: '#1F2937',
    },
    searchInput: {
        flex: 1,
        height: 50,
        backgroundColor: 'transparent',
        fontSize: 16,
        color: '#4B5563',
    },
    packageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 25,
        gap: 20,
    },
    slidableContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        paddingVertical: 12,
        backgroundColor: 'transparent',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingHorizontal: 20,
        marginBottom: 25,
        padding: 18,
        margin: 15,
        elevation: 3,
    },
    packageCard: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderRadius: 30,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
        height: 55,
        width: 140,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: '#E5E7EB',
    },
    packageTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#333333',
        marginBottom: 5,
    },
    customText: {
        color: '#6B7280',
        fontSize: 14,
    },
    enterButton: {
        backgroundColor: '#3B82F6',
        borderRadius: 30,
        paddingVertical: 12,
        paddingHorizontal: 35,
        alignSelf: 'flex-end',
        marginBottom: 35,
    },
    starterSection: {
        backgroundColor: '#F59E0B',
        borderRadius: 30,
        margin: 15,
        padding: 35,
        width: '90%',
        height: 400,
        zIndex: 999,
        marginTop: -40,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 10,
        borderWidth: 1,
        borderColor: '#FFFFFF',
    },
    starterTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 20,
    },
    welcomeText: {
        color: '#D1D5DB',
        marginBottom: 25,
    },
    ctaContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#1F2937',
        padding: 18,
        borderRadius: 55,
        marginTop: 100,
    },
    seeMoreLink: {
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
        marginLeft: 50,
    },
    buyButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 50,
        width: 45,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buyButtonText: {
        color: '#1F2937',
        fontWeight: '700',
    },
    alignStart: {
        alignSelf: 'flex-start',
        color: '#1F2937',
        fontWeight: '600',
        fontSize: 16,
        marginBottom: 12,
    },
    packageDetailsContainer: {
        marginTop: 40,
        padding: 0,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        height: 340,
    },
});

export default styles;
