import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

const styles = StyleSheet.create({
  alignStart: {
    alignSelf: 'flex-start',
    color: Colors.text.primary,
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 14,
    margin: 15,
  },
  animatedView: {
    transform: [{ translateX: 0 }],
  },
  avatar: {
    borderColor: Colors.border.white,
    borderWidth: 3,
    marginLeft: 15,
  },
  avatarOverlay: {
    backgroundColor: Colors.primary,
  },
  buyButton: {
    alignItems: 'center',
    backgroundColor: Colors.background.white,
    borderRadius: 60,
    height: 40,
    justifyContent: 'center',
    width: 50,
  },
  buyButtonText: {
    color: Colors.text.primary,
    fontWeight: '700',
  },
  container: {
    backgroundColor: Colors.background.light,
    flexGrow: 1,
    minHeight: '100%',
    paddingTop: 45,
  },
  ctaContainer: {
    alignItems: 'center',
    backgroundColor: Colors.text.primary,
    borderRadius: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 200,
    padding: 12,
  },
  customText: {
    color: Colors.text.gray,
    fontSize: 15,
  },
  greeting: {
    color: Colors.text.white,
    fontSize: 32,
    fontWeight: '900',
    marginBottom: 8,
  },
  header: {
    backgroundColor: Colors.background.header,
    elevation: 8,
    marginTop: -45,
    paddingHorizontal: 20,
    paddingVertical: 50,
    shadowOffset: { width: 0, height: 10 },
    width: '100%',
  },
  headerContent: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  imageStyle: {
    borderRadius: 30,
  },
  packageCard: {
    alignItems: 'center',
    backgroundColor: Colors.transparent,
    borderColor: Colors.border.light,
    borderRadius: 35,
    elevation: 7,
    height: 55,
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 12,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    width: 150,
  },
  packageContainer: {
    flexDirection: 'row',
    gap: 22,
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  packageDetailsContainer: {
    backgroundColor: Colors.background.white,
    borderRadius: 15,
    elevation: 6,
    height: 350,
    marginTop: 45,
    padding: 0,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  packageTitle: {
    color: Colors.text.secondary,
    fontSize: 16,
    fontWeight: '700',
  },
  searchContainer: {
    alignItems: 'center',
    backgroundColor: Colors.background.white,
    borderColor: Colors.border.light,
    borderRadius: 35,
    borderWidth: 1.5,
    elevation: 5,
    flexDirection: 'row',
    margin: 10,
    paddingHorizontal: 22,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  searchIcon: {
    color: Colors.text.primary,
    marginRight: 18,
  },
  searchInput: {
    backgroundColor: Colors.transparent,
    color: Colors.text.secondary,
    flex: 1,
    fontSize: 16,
    height: 55,
  },
  seeMoreLink: {
    color: Colors.text.white,
    fontWeight: '600',
    marginLeft: 45,
    textAlign: 'center',
  },
  selectedPackageCard: {
    backgroundColor: Colors.text.primary,
  },
  selectedPackageTitle: {
    color: Colors.text.white,
  },
  slidableContainer: {
    alignItems: 'center',
    backgroundColor: Colors.background.white,
    borderColor: Colors.border.white,
    borderRadius: 35,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'center',
    margin: 4,
    marginBottom: 30,
    paddingHorizontal: 22,
    paddingVertical: 14,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  starterSection: {
    backgroundColor: Colors.warning,
    borderRadius: 35,
    elevation: 12,
    height: 460,
    margin: 20,
    marginTop: -45,
    padding: 40,
    position: 'relative',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    width: '90%',
    zIndex: 999,
  },
  starterTitle: {
    color: Colors.text.white,
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 22,
  },
  unselectedPackageCard: {
    backgroundColor: Colors.background.white,
  },
  unselectedPackageTitle: {
    color: Colors.text.black,
  },
  welcome: {
    color: Colors.text.black,
    fontSize: 18,
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
  },
  welcomeText: {
    color: Colors.background.header,
    marginBottom: 30,
  },
});

export default styles;
